# Project identification
sonar.projectKey=postman-testing
sonar.projectName=Postman Testing Application
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes

# Language and encoding
sonar.language=java
sonar.sourceEncoding=UTF-8

# Test coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/model/**,**/config/**

# Exclusions
sonar.exclusions=**/model/**,**/dto/**,**/target/**,**/test/**

# Java specific properties
sonar.java.source=17
sonar.java.target=17